---
api:
  endpoint: https://integrations.expensify.com/Integration-Server/ExpensifyIntegrations
  key: aa_john_smith
  secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
email: john.smith@example.com
report:
  name: Monthly Expenses
  policy_id: XXXXXXXXXXXXXXXX
expenses:
  - merchant: merchant_name
    comment: this is item 1
    category: "Category 1"
    department: "Department 1"
    amount: 1599
    # date: "2018-01-01"
    currency: USD
  - merchant: per
    comment: this is item 2
    amount: 1234
    category: "Category 2"
    # date: "2018-01-01"
    department: "Department 2"
    currency: USD
